### ISSUE TITLE
Failure to complete ten epochs

### ISSUE THREAD

**Issue by RuchirB** [brannondorsey/midi-rnn#4]
Everything was going smoothly, until I realized that the midi-rnn system was stuck on the following:

`"Epoch 1/10"`

I let it run overnight for over 12 hours and it was still stuck. Despite this, it was using up 100% of my CPU! 
![screen shot 2018-01-04 at 10 47 59 am](https://user-images.githubusercontent.com/27583648/34579176-c1f4939e-f13c-11e7-8e27-2fb1e275001a.png)

I had to eventually terminate the process and quit on the training.

**Comment by brannondorsey** [comment]
Hmm... strange indeed. Could you provide as much detail as possible about your platform, training data, and the steps to reproduce as possible? You could also add some debug statements to try and locate where in the script the code is hanging and I could perhaps look into it.

**Comment by RuchirB** [comment]
@brannondorsey Thanks for the response. My platform is Mac OSX and is running Sierra with the Intel HD Graphics 3000 512 MB and a 2.3 GHz Intel Core i5 CPU. I'll try running it again, but what debug statements do you want me to try?

**Comment by RuchirB** [comment]
@brannondorsey  This is extremely odd, all of a sudden I tried running the same line again `Sudo python train.py  --silence_threshold=0 --data_dir=/Users/ruchirbaronia/Desktop/allMidis` and I get this error:

```
Ruchirs-MacBook-Pro:midi-rnn ruchirbaronia$ Sudo python train.py  --silence_threshold=0 --data_dir=/Users/ruchirbaronia/Desktop/allMidis
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    import utils
  File "/Users/ruchirbaronia/midi-rnn/utils.py", line 2, in <module>
    import pretty_midi
ModuleNotFoundError: No module named 'pretty_midi'
```

I'm baffled as to what is going on. Should I start a new issue?

**Comment by brannondorsey** [comment]
I'm assuming you had previously installed `pretty_midi` and it worked fine, right?

Why are you running this as a root user? Try without sudo. Sudo changes the user environment and likely what is happening is that the root user doesn't know where to find your python packages but your regular user does. 

What is the output of:

```bash
which python

# and...
sudo which python
```
Are they pointing to the same python?

**Comment by RuchirB** [comment]
@brannondorsey  Yes, both point to `/anaconda3/bin/python` 

PS: Regarding the second issue, I'm actually not sure what Pretty_midi is, but I somehow fixed it by doing `pip install protobuf==3.4.0`and `pip install pretty_midi`.

**Comment by RuchirB** [comment]
@brannondorsey  Tried again, and midi-rnn is still stuck on epoch 1/10.

![screen shot 2018-01-06 at 12 02 10 pm](https://user-images.githubusercontent.com/27583648/34643464-8275f084-f2d9-11e7-97fa-51b1c8a03c3e.png)

Some more details: My input directory, `allMidis`, is 3.2 MB on disk with 75 midi files. It is stored on my desktop.

**Comment by brannondorsey** [comment]
Dang... I found an issue in an old workshop repo that I used midi-rnn for a while ago, and I noticed [this](https://github.com/brannondorsey/ml4music-workshop/issues/3). It could be related. Do you want to try training a very small subset of your training files and see if it works? Maybe there is a corrupt or otherwise mishandled midi file in there that it is hanging on.
.

**Comment by RuchirB** [comment]
@brannondorsey  Great suggestion! I took four of my 75 midi files and put them in another directory called `fourmidis`, then I ran `python train.py --n_jobs=4 --data_dir=/Users/ruchirbaronia/Desktop/fourmidis`. And look at this crazy error I got:

![screen shot 2018-01-06 at 12 26 09 pm](https://user-images.githubusercontent.com/27583648/34643641-d41e935c-f2dc-11e7-913d-314b06cdf3a3.png)

Here's the copy pasted version:

```
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    main()
  File "train.py", line 233, in main
    initial_epoch=epoch)
  File "/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/keras/models.py", line 1227, in fit_generator
    initial_epoch=initial_epoch)
  File "/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 735, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 635, in data_generator_task
    generator_output = next(self._generator)
  File "/Users/ruchirbaronia/midi-rnn/utils.py", line 93, in get_data_generator
    load_index = (load_index + max_files_in_ram) % len(midi_paths)
ZeroDivisionError: integer division or modulo by zero

```

At this point, I don't even know what's happening haha, sometimes it hangs, sometimes it throws an error...very unpredictable!

**Comment by brannondorsey** [comment]
Would you want to send me contents of `fourmidis` and I could test on my linux machine? I don't have access to a Mac but I could try and throw the same error and debug that on my end on Ubuntu.

**Comment by RuchirB** [comment]
@brannondorsey Sure! Here is the directory I tested with
[fourmidis.zip](https://github.com/brannondorsey/midi-rnn/files/1610012/fourmidis.zip)

**Comment by sricketts** [comment]
I'm also hitting this issue, I think. Out of the box, I can't get stuck at Epoch 1/10. I'm using ubuntu.

Running:
`python train.py --data_dir data/midi/`

I've tried a few different subsets of the midi data. Same problem.

**Comment by sricketts** [comment]
I think I've figured out the issue (at least my issue).

In utils.py, `parse_midi`, for whatever reason, the PrettyMidi constructor is hitting:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 13: invalid continuation byte
```

The try except around that hides the error, so `parse_midi` returns `None`.

So in `get_data_generator`, `parsed` generates no midi objects, and we just spin in the `while True` loop (I'm hand-waving a little here to spare some details). That's why we get stuck at `Epoch 1/10`.

It turns out that, instead of passing a file object to `PrettyMidi`, if I pass the file path, I don't hit the error there, so it returns a midi object. So that fixes the issue for me. I'm not going to dig into `pretty_midi` to figure out how they are reading the file, I'll just naively trust that they are doing it correctly. 

I'll post a pull request shortly, though I'm only going to have tested this on ubuntu, so YMMV.

**Comment by brannondorsey** [comment]
This should now be fixed thanks to @sricketts's update. I'll re-open the issue if the fix doesn't work for folks or upon request.

**Comment by isaacbernat** [comment]
Hi, I think I have the same or a similar issue. I was running `python3 train.py --data_dir midi_songs5`, just 5 scarlatti sonatas for 40 minutes in my 16GB of RAM, Core i7, 2012 Mac but it wouldn't go beyond epoch 1. The CPU usage of a process named Python was about 180%. After killing it (CTRL+C on the terminal with `python3 train.py`) it went down to 99% (instead of 0%) and I eventually had to kill it manually through Activity Monitor (task manager). Could you look into it? I could give you the midi files if you think that would help... Thanks! **PS:** I got this warning after the Epoch 1/10 message `/Users/ec/pypi_venv/lib/python3.7/site-packages/keras/utils/data_utils.py:718: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.`
